inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - Guardfile
    - Gemfile
    - config/*
    - unicorn.conf.rb


# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 80
  AllowURI: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/AndOr:
  Enabled: true

# Cop supports --auto-correct.
Style/Blocks:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/TrailingBlankLines:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: IgnoredMethods.
Style/SymbolProc:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/StringLiterals:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, EnforcedStyleForEmptyBraces, SpaceBeforeBlockParameters.
Style/SpaceInsideBlockBraces:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/SpaceBeforeBlockBraces:
  Enabled: true

# Configuration parameters: MaxSlashes.
Style/RegexpLiteral:
  Enabled: true

# Cop supports --auto-correct.
Style/NumericLiterals:
  MinDigits: 6

# Cop supports --auto-correct.
# Configuration parameters: PreferredDelimiters.
Style/PercentLiteralDelimiters:
  Enabled: true

# Cop supports --auto-correct.
Style/RedundantBegin:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/MethodDefParentheses:
  Enabled: true

# Cop supports --auto-correct.
Style/MethodCallParentheses:
  Enabled: true

# Cop supports --auto-correct.
Style/LeadingCommentSpace:
  Enabled: true

# Cop supports --auto-correct.
Style/IndentationConsistency:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/HashSyntax:
  Enabled: true

# Cop supports --auto-correct.
Style/EmptyLines:
  Enabled: true

# Cop supports --auto-correct.
Style/CommentIndentation:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/AlignParameters:
  Enabled: true

Style/AccessorMethodName:
  Enabled: true

Style/Documentation:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

# Cop supports --auto-correct.
Lint/UnusedBlockArgument:
  Enabled: true

Lint/AmbiguousRegexpLiteral:
  Enabled: true
